create table if not exists public.categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);

create table if not exists public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    email varchar(512) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists public.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation varchar(2048) NOT NULL,
    category_id bigint NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description varchar(8192) NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    user_id bigint NOT NULL,
    lat float NOT NULL,
    lon float NOT NULL,
    paid boolean NOT NULL,
    participant_limit int NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    request_moderation boolean NOT NULL,
    state varchar(16) NOT NULL,
    title varchar(128) NOT NULL,
    CONSTRAINT fk_events_to_categories FOREIGN KEY(category_id) REFERENCES categories(id),
    CONSTRAINT fk_events_to_users FOREIGN KEY(user_id) REFERENCES users(id)
);